### ISSUE TITLE
Movement Terms of Service §  Securities Law Matters contains inaccurate DAO purpose (/docs/dao/legal/tos.md)

### ISSUE THREAD

**Issue by filipviz** [themovementdao/move-docs#6]
`/docs/dao/legal/tos.md` line 93 reads (abridged):

> ...  SINCE THE PURPOSE OF THE DAO IS TO PROVIDE A BLOCKCHAIN NATIVE ACCOUNTING APPLICATION, PROVIDE NO RIGHTS TO ANY DISTRIBUTION OR PROFITS, AND ARE NON-TRANSFERABLE EXCEPT DETAILED IN THE TERMS OF USE.

Suggested revision:

> ... **CONSIDERED OR REGARDED AS SECURITIES AS** THE PURPOSE OF THE DAO IS TO PROVIDE A BLOCKCHAIN NATIVE **TREASURY MANAGEMENT** APPLICATION **AND THE DAO TOKENS** PROVIDE NO RIGHTS TO ANY DISTRIBUTION OR PROFITS, AND ARE NON-TRANSFERABLE EXCEPT **AS** DETAILED IN THE TERMS OF USE.

**Comment by tankbottoms** [comment]
Accepted the changes.
