### ISSUE TITLE
Governance token allocation

### ISSUE THREAD

**Issue by Sal1y-H** [themovementdao/move-docs#8]
Should it highlight how many of the airdropped tokens were taken up?  When I read it I immediately wonder 'so how many of those people are actively involved?'

**Comment by tankbottoms** [comment]
> Should it highlight how many of the airdropped tokens were taken up? When I read it I immediately wonder 'so how many of those people are actively involved?'

which the NFTs or the token allocation which hasn't happened?

**Comment by tankbottoms** [comment]
Addressed in the documentation.

**Comment by Sal1y-H** [comment]
> > Should it highlight how many of the airdropped tokens were taken up? When I read it I immediately wonder 'so how many of those people are actively involved?'
> 
> which the NFTs or the token allocation which hasn't happened?

The NFT.
